name: Main

on:
  push:
    branches: [main]
    tags: [v*.*.*]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  prek:
    name: Prek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run prek
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0

  test:
    name: Test
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run tests
        run: make test

      - name: Upload coverage
        uses: deadnews/coverage-badge-action@bc4aaf332f25c52d1e8dd21ef9ed0b2337ad39af # v1.0.0
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        with:
          file: coverage.txt
          type: go

  pypi-deploy:
    name: Release to PyPI
    if: github.ref_type == 'tag'
    needs: [prek, test]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Build wheels
        uses: deadnews/go-wheel-action@35c6f5b9ffdd11dbdc7043ea3ef71372aa6f2fe7 # v1.0.3
        with:
          package: ./cmd/pindock
          ldflags: -s -X main.version=${{ github.ref_name }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2

  github-deploy:
    name: Release to GitHub
    if: github.ref_type == 'tag'
    needs: [prek, test]
    environment: github-releases
    permissions:
      contents: write
    env:
      PRERELEASE: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          args: release --clean --draft=${{ env.PRERELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  aur-deploy:
    name: Release to AUR
    if: true && !contains(github.ref, 'alpha') && !contains(github.ref, 'beta')
    needs: [github-deploy]
    environment:
      name: aur
      url: https://aur.archlinux.org/packages/${{ github.event.repository.name }}-bin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Update version in PKGBUILD
        run: |
          pkgver="${GITHUB_REF_NAME#v}"
          pkgver="${pkgver//-/_}"
          sed "s|^pkgver=.*$|pkgver=\"${pkgver}\"|" -i PKGBUILD

      - name: Deploy PKGBUILD to the AUR
        uses: ksxgithub/github-actions-deploy-aur@084b0d9b15415bf9cdb65d44dad1efe37a354050 # v4.2.0
        with:
          pkgname: ${{ github.event.repository.name }}-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ github.actor }}
          commit_email: ${{ github.actor }}@users.noreply.github.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Upstream release ${{ github.ref_name }}
          updpkgsums: true
          test: true
